version: "3"

services:
  postgres:
    container_name: local-postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    hostname: postgres
    environment:
      # PGDATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Load web UI for postgres
  # http://localhost:8080/?pgsql=postgres&username=postgres&db=postgres&ns=public
  postgres-ui:
    container_name: local-postgres-ui
    image: adminer:latest
    depends_on:
      - postgres
    ports:
      - 8080:8080
    hostname: postgres-ui
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=pepa-linha
